### ISSUE TITLE
Update DegCre to 1.1.1

### ISSUE THREAD

**Issue by brianSroberts** [Bioconductor/gha-build-rstudio-release-amd64#1]
I'm going to push an update of the DegCre package to 1.1.1.

**Comment by brianSroberts** [comment]
When it try to push it errors:
"remote: Error: Illegal version bump from '1.1.0' to '1.2.0'."

I think 1.20 is appropriate for this release (new functions, changes to core functions.) I changed it to 1.20 because BiocCheck warns that the "y" digit of the version should be even for stable releases.

Not sure what to do here.

**Comment by almahmoud** [comment]
Hey @brianSroberts. This is an internal automated repository, and not the best place to raise this. Please use the #developers-forum channel on slack.bioconductor.org, or the mailing list bioc-devel@r-project.org .

Personally, I think this is a valid concern, and don't personally like how the Bioconductor-driven bumps can ambiguate the meaning behind development-driven versioning, and will raise it at the team meeting as a general issue, but until we make a change to Bioconductor versioning policies, I think you should seek guidance on how to version bump in your specific case from other developers and team members through one of the channels above.

**Comment by brianSroberts** [comment]
Thanks for the help. I'll move this to the email list.
